### ISSUE TITLE
需求: 统计维度

### ISSUE THREAD

**Issue by crossz** [xiaoyao2102/betting-strategy#1]
## 运营统计：
1. 连续n场比赛的最好/最差运营风险表现
2. 以hdc线分组，风险表现是不是一致；或风险表现有何差异
3. 以hilo线分组，风险表现是不是一致；或风险表现有何差异
4. 彩民盈亏的比例（在投注都一致的情况下）
5. Margin 与 以上各个统计的关系
## 交易策略之进球了：
1. 强队率先进球，立刻交易各个选项的利润表现有何差异
2. 弱队率先进球，立刻交易各个选项的利润表现有何差异
## 交易策略之赔率变化趋势：
1. 统计：在没有进球发生的前提下，以hdc线分组，挖掘 decay 的趋势
2. 前15分钟，与统计的趋势有偏差，进行交易与不交易，利润表现有何差异

**Comment by xiaoyao2102** [comment]
## 运营统计：
1. 一定要连续n场么？风险表现就是指盈收？
1. 怎么以hdc线分组？
1. 怎么以hilo线分组？

## 交易策略之进球了：
1. 比赛之前选项全包么？

(￣▽￣")

**Comment by crossz** [comment]
如果比赛场次少，难以说明中长期运营的表现；如果比赛足够多，可以按照hdc／hilo分组统计和讨论。

运营统计，在没有细化入场和CO的策略的时候，那就先来个比较随机的方式，要么按比例全包，要么随机买选项。

**Comment by xiaoyao2102** [comment]
目前的做法是把数据全写入MySQL，然后可以用SQL进行各种维度的查询。But it remains a question how to display the result elegantly

**Comment by crossz** [comment]
写入MySQL就行，怎么展示，可以交给其他人（比如我）

**Comment by xiaoyao2102** [comment]
好，那目前Analysis模块就做到写入数据这一步。1.5的testing数据库operations和result是我建的两张表，您有空可以看下。
