### ISSUE TITLE
需求: LoadData 中的 sql 可以自定义

### ISSUE THREAD

**Issue by crossz** [xiaoyao2102/betting-strategy#3]
现在的是：
`sql = 'SELECT europe_id FROM company_odds_history ORDER BY RAND() LIMIT %d' % game_num`

有的时候，需要自定义一下，比如：
`sql = 'SELECT DISTINCT europe_id FROM company_odds_history where update_time > "2016-09-17 00:00:01" ORDER BY update_time'`

**Comment by xiaoyao2102** [comment]
OK，分分钟
