### ISSUE TITLE
需求：Strategy 解耦于 Analysis 之 getResult 和 getOperation

### ISSUE THREAD

**Issue by crossz** [xiaoyao2102/betting-strategy#6]
用特定方法返回 result和operation的list，替换在Strategy中直接入库的方式。

**Comment by crossz** [comment]
赶脚 StrategyInvestor 和  Analyzer 耦合的越来越紧了。

比如 MemoryAnalyzer 中的两个方法：
1) insert_operation 在 Strategy 的 store_operation 方法中；
2) insert_result 在 Strategy 的 game_processing 方法中；

说有逻辑也有逻辑，说耦合的乱也是乱。

我脚着应该是：

for ..... :
    # 应用 strategy，返回一个 invester 的 instance，这里包含了这个strategy的全部信息
    i = WhoScoreInvestor(game, Analyzer, strong_team=True)

    # 应用 analysor，获取 i.operation_list, i.result_dict后
    a  = xxxxAnalysor(i.operation_list, i.result_dict)


如此，可以把 strategy 和 analysor 解开。

**Comment by xiaoyao2102** [comment]
有道理，这个方法好 :thumbsup:
