### ISSUE TITLE
需求: 各个具体的Strategy的买和卖的方法做成static的

### ISSUE THREAD

**Issue by crossz** [xiaoyao2102/betting-strategy#8]
为了便于后期各种进入和退出的方式的混合，静态的调用这些方法，更为方便。

**Comment by xiaoyao2102** [comment]
可以。。不过这么做感觉很奇怪，好像跟类就没什么关系了，不如直接写一堆方法，愿意用哪个就调哪个。

**Comment by crossz** [comment]
嗯，这个需求不急，先琢磨琢磨，怎么弄更好一些。如果做成util那些，自然也是很好的。
